version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=defaultUser
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=laravel-testdb
      - MARIADB_ROOT_PASSWORD=password
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=defaultUser
      - DB_DATABASE=laravel-testdb
      - DB_PASSWORD=password
      - FILESYSTEM_DISK=public
       
    volumes:
      - './project:/app'
    depends_on:
      - mariadb
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 8080:8080
